baseURL: https://andreaslongo.github.io/asciidoctor-diagram-hugo-docsy
title: Example
theme:
  - docsy
markup:
  asciidocExt:
    extensions: ["asciidoctor-diagram"]
    workingFolderCurrent: true
    attributes:
      diagram-cachedir: .cache


###############################################################################
# Privacy settings
# https://gohugo.io/about/hugo-and-gdpr/
###############################################################################

privacy:
  disqus:
    disable: true
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true


###############################################################################
# Security settings
# https://gohugo.io/about/security-model/
###############################################################################

security:
  enableInlineShortcodes: false
  exec:
    allow:
    - ^asciidoctor$
    - ^dart-sass-embedded$
    - ^go$
    - ^npx$
    - ^postcss$
